# Copyright (C) 2026 Phyxor Microsystems
# SPDX-FileContributor: Pablo Palazon
#
# SPDX-License-Identifier: BSD-3-Clause

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^mkdocs\.yml$
      - id: check-toml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: reuse-annotate
        name: reuse annotate
        entry: >-
          bash -c 'reuse annotate --contributor "$(git config --get user.name)" -c "Phyxor Microsystems" -l BSD-3-Clause --copyright-prefix string-c --merge-copyrights --skip-unrecognised "$@"' --
        language: system
        exclude: ^vendor/
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: ^(?!vendor/).*\.(c|h)$
      - id: reuse
        name: reuse lint
        entry: reuse lint
        language: system
        pass_filenames: false
