site_name: Blue Pill Bare-Metal
copyright: Copyright &copy; 2026 Pablo Palazón
docs_dir: docs

extra:
  generator: true

nav:
  - Memory Map: stm32f103c8t6-memory-map.md
  - Build Process: build-process.md
  - Linker And Startup: linker-startup.md
  - Applications:
      - Blink: apps/blink.md
  - Reference:
      - Acronyms: acronyms.md
      - PDFs:
          - CKS32F103x Datasheet: refs/CKS32F103x.pdf
          - CKS32F103x Reference Manual: refs/CKS32F103x8-reference-manual.pdf
          - STM32F103x8 Datasheet: refs/stm32f103x8-datasheet.pdf
          - STM32F103x8 Reference Manual: refs/stm32f103x8-reference.pdf
          - ARM Cortex-M3 User Guide: refs/arm-cortex-m3-generic-user-guide.pdf

theme:
  name: material
  palette:
    primary: blue grey
    accent: orange
  font:
    text: Saira
    code: JetBrains Mono
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2
