#ifndef STM32F103C8T6_H
#define STM32F103C8T6_H

#include <stdint.h>

/*
 * Minimal STM32F103C8T6 register map for bare-metal learning.
 * This is intentionally smaller than the vendor CMSIS device header.
 */

#define STM32_REG32(addr) (*(volatile uint32_t *)(uintptr_t)(addr))
#define STM32_BIT(n) (1u << (n))

/* Top-level Cortex-M3 memory regions. */
#define STM32_CODE_BASE 0x00000000u
#define STM32_SRAM_REGION_BASE 0x20000000u
#define STM32_PERIPH_REGION_BASE 0x40000000u
#define STM32_EXT_RAM_BASE 0x60000000u
#define STM32_EXT_DEVICE_BASE 0xA0000000u
#define STM32_PPB_BASE 0xE0000000u

/* STM32F103C8T6 on-chip memory. */
#define STM32_BOOT_ALIAS_BASE 0x00000000u
#define STM32_FLASH_BASE 0x08000000u
#define STM32_FLASH_SIZE_BYTES (64u * 1024u)
#define STM32_FLASH_END (STM32_FLASH_BASE + STM32_FLASH_SIZE_BYTES - 1u)

#define STM32_SYSTEM_MEMORY_BASE 0x1FFFF000u
#define STM32_SYSTEM_MEMORY_END 0x1FFFF7FFu
#define STM32_FLASH_SIZE_REG_ADDR 0x1FFFF7E0u
#define STM32_UID_BASE 0x1FFFF7E8u
#define STM32_OPTION_BYTES_BASE 0x1FFFF800u
#define STM32_OPTION_BYTES_END 0x1FFFF80Fu

#define STM32_SRAM_BASE 0x20000000u
#define STM32_SRAM_SIZE_BYTES (20u * 1024u)
#define STM32_SRAM_END (STM32_SRAM_BASE + STM32_SRAM_SIZE_BYTES - 1u)

/* Cortex-M3 bit-band regions. */
#define STM32_SRAM_BITBAND_BASE 0x20000000u
#define STM32_SRAM_BITBAND_ALIAS_BASE 0x22000000u
#define STM32_PERIPH_BITBAND_BASE 0x40000000u
#define STM32_PERIPH_BITBAND_ALIAS_BASE 0x42000000u

#define STM32_BITBAND_ALIAS(alias_base, bitband_base, addr, bit)                                   \
    ((alias_base) + (((uint32_t)(addr) - (bitband_base)) * 32u) + ((uint32_t)(bit) * 4u))

#define STM32_SRAM_BIT_ALIAS(addr, bit)                                                            \
    STM32_BITBAND_ALIAS(STM32_SRAM_BITBAND_ALIAS_BASE, STM32_SRAM_BITBAND_BASE, (addr), (bit))

#define STM32_PERIPH_BIT_ALIAS(addr, bit)                                                          \
    STM32_BITBAND_ALIAS(STM32_PERIPH_BITBAND_ALIAS_BASE, STM32_PERIPH_BITBAND_BASE, (addr), (bit))

/* APB1 peripheral bases. */
#define TIM2_BASE 0x40000000u
#define TIM3_BASE 0x40000400u
#define TIM4_BASE 0x40000800u
#define RTC_BASE 0x40002800u
#define WWDG_BASE 0x40002C00u
#define IWDG_BASE 0x40003000u
#define SPI2_BASE 0x40003800u
#define USART2_BASE 0x40004400u
#define USART3_BASE 0x40004800u
#define I2C1_BASE 0x40005400u
#define I2C2_BASE 0x40005800u
#define USB_BASE 0x40005C00u
#define USB_CAN_SRAM_BASE 0x40006000u
#define CAN_BASE 0x40006400u
#define BKP_BASE 0x40006C00u
#define PWR_BASE 0x40007000u

/* APB2 peripheral bases. */
#define AFIO_BASE 0x40010000u
#define EXTI_BASE 0x40010400u
#define GPIOA_BASE 0x40010800u
#define GPIOB_BASE 0x40010C00u
#define GPIOC_BASE 0x40011000u
#define GPIOD_BASE 0x40011400u
#define ADC1_BASE 0x40012400u
#define ADC2_BASE 0x40012800u
#define TIM1_BASE 0x40012C00u
#define SPI1_BASE 0x40013000u
#define USART1_BASE 0x40013800u

/* AHB peripheral bases. */
#define DMA1_BASE 0x40020000u
#define RCC_BASE 0x40021000u
#define FLASH_INTERFACE_BASE 0x40022000u
#define CRC_BASE 0x40023000u

/* Cortex-M3 core peripheral bases. */
#define SCS_BASE 0xE000E000u
#define SYSTICK_BASE 0xE000E010u
#define NVIC_BASE 0xE000E100u
#define SCB_BASE 0xE000ED00u
#define MPU_TYPE_ADDR 0xE000ED90u
#define STIR_ADDR 0xE000EF00u

/* Register helpers. */
#define RCC_REG(offset) STM32_REG32(RCC_BASE + (offset))
#define FLASH_REG(offset) STM32_REG32(FLASH_INTERFACE_BASE + (offset))
#define GPIO_REG(base, offset) STM32_REG32((base) + (offset))
#define AFIO_REG(offset) STM32_REG32(AFIO_BASE + (offset))
#define EXTI_REG(offset) STM32_REG32(EXTI_BASE + (offset))
#define SYSTICK_REG(offset) STM32_REG32(SYSTICK_BASE + (offset))
#define SCB_REG(offset) STM32_REG32(SCB_BASE + (offset))

/* RCC register offsets. */
#define RCC_CR_OFFSET 0x00u
#define RCC_CFGR_OFFSET 0x04u
#define RCC_CIR_OFFSET 0x08u
#define RCC_APB2RSTR_OFFSET 0x0Cu
#define RCC_APB1RSTR_OFFSET 0x10u
#define RCC_AHBENR_OFFSET 0x14u
#define RCC_APB2ENR_OFFSET 0x18u
#define RCC_APB1ENR_OFFSET 0x1Cu
#define RCC_BDCR_OFFSET 0x20u
#define RCC_CSR_OFFSET 0x24u

/* Flash interface register offsets. */
#define FLASH_ACR_OFFSET 0x00u

#define RCC_CR RCC_REG(RCC_CR_OFFSET)
#define RCC_CFGR RCC_REG(RCC_CFGR_OFFSET)
#define RCC_CIR RCC_REG(RCC_CIR_OFFSET)
#define RCC_APB2RSTR RCC_REG(RCC_APB2RSTR_OFFSET)
#define RCC_APB1RSTR RCC_REG(RCC_APB1RSTR_OFFSET)
#define RCC_AHBENR RCC_REG(RCC_AHBENR_OFFSET)
#define RCC_APB2ENR RCC_REG(RCC_APB2ENR_OFFSET)
#define RCC_APB1ENR RCC_REG(RCC_APB1ENR_OFFSET)
#define RCC_BDCR RCC_REG(RCC_BDCR_OFFSET)
#define RCC_CSR RCC_REG(RCC_CSR_OFFSET)

#define FLASH_ACR FLASH_REG(FLASH_ACR_OFFSET)

/* RCC control and clock enable bits. */
#define RCC_CR_HSION STM32_BIT(0)

#define RCC_AHBENR_DMA1EN STM32_BIT(0)
#define RCC_AHBENR_SRAMEN STM32_BIT(2)
#define RCC_AHBENR_FLITFEN STM32_BIT(4)
#define RCC_AHBENR_CRCEN STM32_BIT(6)

#define RCC_APB2ENR_AFIOEN STM32_BIT(0)
#define RCC_APB2ENR_IOPAEN STM32_BIT(2)
#define RCC_APB2ENR_IOPBEN STM32_BIT(3)
#define RCC_APB2ENR_IOPCEN STM32_BIT(4)
#define RCC_APB2ENR_IOPDEN STM32_BIT(5)
#define RCC_APB2ENR_ADC1EN STM32_BIT(9)
#define RCC_APB2ENR_ADC2EN STM32_BIT(10)
#define RCC_APB2ENR_TIM1EN STM32_BIT(11)
#define RCC_APB2ENR_SPI1EN STM32_BIT(12)
#define RCC_APB2ENR_USART1EN STM32_BIT(14)

#define RCC_APB1ENR_TIM2EN STM32_BIT(0)
#define RCC_APB1ENR_TIM3EN STM32_BIT(1)
#define RCC_APB1ENR_TIM4EN STM32_BIT(2)
#define RCC_APB1ENR_WWDGEN STM32_BIT(11)
#define RCC_APB1ENR_SPI2EN STM32_BIT(14)
#define RCC_APB1ENR_USART2EN STM32_BIT(17)
#define RCC_APB1ENR_USART3EN STM32_BIT(18)
#define RCC_APB1ENR_I2C1EN STM32_BIT(21)
#define RCC_APB1ENR_I2C2EN STM32_BIT(22)
#define RCC_APB1ENR_USBEN STM32_BIT(23)
#define RCC_APB1ENR_CANEN STM32_BIT(25)
#define RCC_APB1ENR_BKPEN STM32_BIT(27)
#define RCC_APB1ENR_PWREN STM32_BIT(28)

/* GPIO register offsets. */
#define GPIO_CRL_OFFSET 0x00u
#define GPIO_CRH_OFFSET 0x04u
#define GPIO_IDR_OFFSET 0x08u
#define GPIO_ODR_OFFSET 0x0Cu
#define GPIO_BSRR_OFFSET 0x10u
#define GPIO_BRR_OFFSET 0x14u
#define GPIO_LCKR_OFFSET 0x18u

#define GPIO_CRL(base) GPIO_REG((base), GPIO_CRL_OFFSET)
#define GPIO_CRH(base) GPIO_REG((base), GPIO_CRH_OFFSET)
#define GPIO_IDR(base) GPIO_REG((base), GPIO_IDR_OFFSET)
#define GPIO_ODR(base) GPIO_REG((base), GPIO_ODR_OFFSET)
#define GPIO_BSRR(base) GPIO_REG((base), GPIO_BSRR_OFFSET)
#define GPIO_BRR(base) GPIO_REG((base), GPIO_BRR_OFFSET)
#define GPIO_LCKR(base) GPIO_REG((base), GPIO_LCKR_OFFSET)

#define GPIOA_CRL GPIO_CRL(GPIOA_BASE)
#define GPIOA_CRH GPIO_CRH(GPIOA_BASE)
#define GPIOA_IDR GPIO_IDR(GPIOA_BASE)
#define GPIOA_ODR GPIO_ODR(GPIOA_BASE)
#define GPIOA_BSRR GPIO_BSRR(GPIOA_BASE)
#define GPIOA_BRR GPIO_BRR(GPIOA_BASE)

#define GPIOB_CRL GPIO_CRL(GPIOB_BASE)
#define GPIOB_CRH GPIO_CRH(GPIOB_BASE)
#define GPIOB_IDR GPIO_IDR(GPIOB_BASE)
#define GPIOB_ODR GPIO_ODR(GPIOB_BASE)
#define GPIOB_BSRR GPIO_BSRR(GPIOB_BASE)
#define GPIOB_BRR GPIO_BRR(GPIOB_BASE)

#define GPIOC_CRL GPIO_CRL(GPIOC_BASE)
#define GPIOC_CRH GPIO_CRH(GPIOC_BASE)
#define GPIOC_IDR GPIO_IDR(GPIOC_BASE)
#define GPIOC_ODR GPIO_ODR(GPIOC_BASE)
#define GPIOC_BSRR GPIO_BSRR(GPIOC_BASE)
#define GPIOC_BRR GPIO_BRR(GPIOC_BASE)

#define GPIOD_CRL GPIO_CRL(GPIOD_BASE)
#define GPIOD_CRH GPIO_CRH(GPIOD_BASE)
#define GPIOD_IDR GPIO_IDR(GPIOD_BASE)
#define GPIOD_ODR GPIO_ODR(GPIOD_BASE)
#define GPIOD_BSRR GPIO_BSRR(GPIOD_BASE)
#define GPIOD_BRR GPIO_BRR(GPIOD_BASE)

/* GPIO pin and configuration helpers. */
#define GPIO_PIN(n) STM32_BIT(n)
#define GPIO_PIN_0 STM32_BIT(0)
#define GPIO_PIN_1 STM32_BIT(1)
#define GPIO_PIN_2 STM32_BIT(2)
#define GPIO_PIN_3 STM32_BIT(3)
#define GPIO_PIN_4 STM32_BIT(4)
#define GPIO_PIN_5 STM32_BIT(5)
#define GPIO_PIN_6 STM32_BIT(6)
#define GPIO_PIN_7 STM32_BIT(7)
#define GPIO_PIN_8 STM32_BIT(8)
#define GPIO_PIN_9 STM32_BIT(9)
#define GPIO_PIN_10 STM32_BIT(10)
#define GPIO_PIN_11 STM32_BIT(11)
#define GPIO_PIN_12 STM32_BIT(12)
#define GPIO_PIN_13 STM32_BIT(13)
#define GPIO_PIN_14 STM32_BIT(14)
#define GPIO_PIN_15 STM32_BIT(15)

#define GPIO_MODE_INPUT 0x0u
#define GPIO_MODE_OUTPUT_10MHZ 0x1u
#define GPIO_MODE_OUTPUT_2MHZ 0x2u
#define GPIO_MODE_OUTPUT_50MHZ 0x3u

#define GPIO_CNF_INPUT_ANALOG 0x0u
#define GPIO_CNF_INPUT_FLOATING 0x1u
#define GPIO_CNF_INPUT_PULL 0x2u
#define GPIO_CNF_OUTPUT_PP 0x0u
#define GPIO_CNF_OUTPUT_OD 0x1u
#define GPIO_CNF_ALT_OUTPUT_PP 0x2u
#define GPIO_CNF_ALT_OUTPUT_OD 0x3u

#define GPIO_CFG_SHIFT(pin) (((pin) & 0x7u) * 4u)
#define GPIO_CFG_MASK(pin) (0xFu << GPIO_CFG_SHIFT(pin))
#define GPIO_CFG(pin, mode, cnf) ((((cnf) << 2u) | (mode)) << GPIO_CFG_SHIFT(pin))

/* AFIO register offsets and common bits. */
#define AFIO_EVCR_OFFSET 0x00u
#define AFIO_MAPR_OFFSET 0x04u
#define AFIO_EXTICR1_OFFSET 0x08u
#define AFIO_EXTICR2_OFFSET 0x0Cu
#define AFIO_EXTICR3_OFFSET 0x10u
#define AFIO_EXTICR4_OFFSET 0x14u

#define AFIO_EVCR AFIO_REG(AFIO_EVCR_OFFSET)
#define AFIO_MAPR AFIO_REG(AFIO_MAPR_OFFSET)
#define AFIO_EXTICR1 AFIO_REG(AFIO_EXTICR1_OFFSET)
#define AFIO_EXTICR2 AFIO_REG(AFIO_EXTICR2_OFFSET)
#define AFIO_EXTICR3 AFIO_REG(AFIO_EXTICR3_OFFSET)
#define AFIO_EXTICR4 AFIO_REG(AFIO_EXTICR4_OFFSET)

#define AFIO_MAPR_SWJ_CFG_MASK (0x7u << 24)
#define AFIO_MAPR_SWJ_CFG_FULL_SWJ (0x0u << 24)
#define AFIO_MAPR_SWJ_CFG_NO_JNTRST (0x1u << 24)
#define AFIO_MAPR_SWJ_CFG_SWD_ONLY (0x2u << 24)
#define AFIO_MAPR_SWJ_CFG_DISABLED (0x4u << 24)

/* EXTI register offsets and helpers. */
#define EXTI_IMR_OFFSET 0x00u
#define EXTI_EMR_OFFSET 0x04u
#define EXTI_RTSR_OFFSET 0x08u
#define EXTI_FTSR_OFFSET 0x0Cu
#define EXTI_SWIER_OFFSET 0x10u
#define EXTI_PR_OFFSET 0x14u

#define EXTI_IMR EXTI_REG(EXTI_IMR_OFFSET)
#define EXTI_EMR EXTI_REG(EXTI_EMR_OFFSET)
#define EXTI_RTSR EXTI_REG(EXTI_RTSR_OFFSET)
#define EXTI_FTSR EXTI_REG(EXTI_FTSR_OFFSET)
#define EXTI_SWIER EXTI_REG(EXTI_SWIER_OFFSET)
#define EXTI_PR EXTI_REG(EXTI_PR_OFFSET)

#define EXTI_LINE(n) STM32_BIT(n)

/* SysTick register offsets and bits. */
#define SYSTICK_CTRL_OFFSET 0x00u
#define SYSTICK_LOAD_OFFSET 0x04u
#define SYSTICK_VAL_OFFSET 0x08u
#define SYSTICK_CALIB_OFFSET 0x0Cu

#define SYSTICK_CTRL SYSTICK_REG(SYSTICK_CTRL_OFFSET)
#define SYSTICK_LOAD SYSTICK_REG(SYSTICK_LOAD_OFFSET)
#define SYSTICK_VAL SYSTICK_REG(SYSTICK_VAL_OFFSET)
#define SYSTICK_CALIB SYSTICK_REG(SYSTICK_CALIB_OFFSET)

#define SYSTICK_CTRL_ENABLE STM32_BIT(0)
#define SYSTICK_CTRL_TICKINT STM32_BIT(1)
#define SYSTICK_CTRL_CLKSOURCE STM32_BIT(2)
#define SYSTICK_CTRL_COUNTFLAG STM32_BIT(16)

#endif /* STM32F103C8T6_H */
